### ISSUE TITLE
Contribution checklist

### ISSUE THREAD

**Issue by Dolu1990** [SpinalHDL/SpinalHDL#619]
Contributor Checklist

- [ ] First open a issue to discuss before implementing changes/features
- [x] Did you add some test code?
- [x] Did you add appropriate documentation in docs/src?
- [x] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release

**Comment by Readon** [comment]
what about the test code, it seems also important to avoid bugs.

**Comment by Dolu1990** [comment]
@Readon added ^^

**Comment by Readon** [comment]
> @Readon added ^^

TDD is fantastic. ^^

**Comment by numero-744** [comment]
What about replacing this pinned issue by a [PR template?](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

**Comment by numero-744** [comment]
Agreed for the CONTRIBUTOR file, to help / guide contributors, it would also describe file structure (#902) and other things?

A PR template could also be helpful for both contributors and maintainers, to really act as a checklist.

I'll open a PR for both CONTRIBUTOR and PR template.
